AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    "PagesController#show",
    "UsersController#create",
    "SubjectsController#index",
    "SubjectsController#create",
    "SubjectsController#subject_params",
    "Admin::ChaptersController#create",
    "Admin::QuestionsController#create",
    "ChaptersController#chapter_params",
    "TestController#create",
    "Admin::AnswersController#create",
    "ChaptersController#chapter_params",
    "ChaptersController#index",
    "ChaptersController#show",
    "Admin::ChaptersController#index",
    "Admin::ChaptersController#show",
    "Admin::ChaptersController#edit",
    "Admin::ChaptersController#update",
    "Admin::SubjectsController#show",
    "Admin::SubjectsController#edit",
    "Admin::SubjectsController#update",
    "SubjectsController#show",
    "UsersController#index",
    "UsersController#show",
    "UsersController#edit",
    "UsersController#update",
    "Admin::AnswersController#index",
    "Admin::AnswersController#show",
    "Admin::AnswersController#edit",
    "Admin::AnswersController#update",
    "Admin::QuestionsController#index",
    "Admin::QuestionsController#show",
    "Admin::QuestionsController#edit",
    "Admin::QuestionsController#update",
    "Admin::TestsController#index",
    "Admin::TestsController#show",
    "Admin::TestsController#test_params",
    "Admin::ResultsController#index",
    "Admin::ResultsController#show",
    "Admin::ResultsController#result_params"
  ]
}
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: {
  except_methods: [
    "TestQuestion#check"
  ]
}
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
